### ISSUE TITLE
Change favicon link

### ISSUE THREAD

**Issue by fahmiegerton** [krehak/laravel-mix-favicon#7]
Hi, may I ask how to change the link of favicon's resources? I've got error 404 for every favicon and manifest generated by this dependency if I visit the page other than `/` (I'm using vue spa so I didn't include the `favicon.blade.php`, only on `app.blade.php`). Thank you!

![image](https://user-images.githubusercontent.com/5303871/134889372-11cd2264-adbe-4e4f-886b-78f8d54a761a.png)

**Comment by krehak** [comment]
Hi!
I'm sorry for late response, but I'm pretty busy these days.

Anyway, it is actually very simple. Just update the `output` option, ie:
```
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        //
    ])
    .favicon({
        output: '/img/favicon',
    });
```
